name: Jekyll site CI

on: [push, pull_request]

jobs:
  build:

    runs-on: openjdk:8-jre

    steps:
    - uses: actions/checkout@v2
    - uses: kamiazya/setup-graphviz@v1
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash \
          -c "chmod 777 /srv/jekyll && jekyll build --future"
