name: Jekyll site CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - uses: kamiazya/setup-graphviz@v1
    - name: Get libfontconfig
      run: |
        sudo apt-get install -y libfontconfig
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash \
          -c "chmod 777 /srv/jekyll && jekyll build --future"
